name: Docker Build Check

on:
  push:
    branches: [main, next]
  pull_request:
    types: [opened, reopened, synchronize]

permissions:
  contents: read
  id-token: write

jobs:
  docker-build:
    runs-on: warp-ubuntu-latest-x64-8x
    strategy:
      matrix:
        include:
          - component: node
            bin: miden-node
            port: 57291
          - component: validator
            bin: miden-validator
            port: 50101
          - component: ntx-builder
            bin: miden-ntx-builder
            port: 50301
    name: Build ${{ matrix.component }}
    steps:
      - name: Build
        uses: WarpBuilds/build-push-action@8c1f3b8bd22c68607865d99ff650d37a564229a5 # v6.0.7
        with:
          push: false
          file: ./Dockerfile
          platforms: linux/amd64
          profile-name: ${{ vars.WARPBUILD_DOCKER_BUILDER_PROFILE }}
          build-args: |
            BIN=${{ matrix.bin }}
            PORT=${{ matrix.port }}
