name: Publish Node Docker Image

on:
  release:
    types: [prereleased, released]

  workflow_dispatch:
    inputs:
      version:
        description: "Version to release (E.G. v0.10.0-rc.1, v0.10.0). Corresponding git tag must already exist."
        required: true
        type: string

env:
  version: ${{ inputs.version || github.ref_name }}
  registry: ghcr.io

permissions:
  id-token: write
  contents: write
  packages: write
  attestations: write

jobs:
  publish:
    runs-on: warp-ubuntu-latest-x64-8x
    environment: publish-docker
    strategy:
      matrix:
        include:
          - component: node
            bin: miden-node
            port: 57291
          - component: validator
            bin: miden-validator
            port: 50101
          - component: ntx-builder
            bin: miden-ntx-builder
            port: 50301
    name: Publish ${{ matrix.component }} ${{ inputs.version }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
        with:
          ref: ${{ env.version }}
          fetch-depth: 0
          persist-credentials: false

      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ env.registry }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        id: push
        uses: WarpBuilds/build-push-action@8c1f3b8bd22c68607865d99ff650d37a564229a5 # v6.0.7
        with:
          context: .
          push: true
          file: ./Dockerfile
          platforms: linux/amd64
          profile-name: ${{ vars.WARPBUILD_DOCKER_BUILDER_PROFILE }}
          build-args: |
            BIN=${{ matrix.bin }}
            PORT=${{ matrix.port }}
          tags: ${{ env.registry }}/0xmiden/miden-${{ matrix.component }}:${{ env.version }}
